FROM nubificus/jetson-inference-updated:x86_64

# Install common build utilities
RUN sed -i '/developer\.download\.nvidia\.com\/compute\/cuda\/repos/d' /etc/apt/sources.list.d/* && \
	sed -i '/developer\.download\.nvidia\.com\/compute\/machine-learning\/repos/d' /etc/apt/sources.list.d/* && \
	apt-key del 7fa2af80 && cd /tmp && \
	wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-keyring_1.0-1_all.deb && \
	dpkg -i cuda-keyring_1.0-1_all.deb && \
	mkdir /guest && apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get install -yy eatmydata && \
	DEBIAN_FRONTEND=noninteractive eatmydata \
	apt-get install -y --no-install-recommends \
		bison \
		flex \
		build-essential \
		libglib2.0-dev \
		libfdt-dev \
		libpixman-1-dev \
		zlib1g-dev \
		pkg-config \
		iproute2 \
		libcap-ng-dev \
		libattr1-dev \
		genisoimage \
		unzip \
		apt-transport-https ca-certificates \
		$(apt-get -s build-dep qemu | egrep ^Inst | fgrep '[all]' | cut -d\  -f2) \
	&& rm -rf /var/lib/apt/lists/* && update-ca-certificates

# Get & install vaccelrti
RUN wget -q https://s3.nbfc.io/nbfc-assets/github/vaccelrt/master/x86_64/Release-deb/vaccel-0.5.0-Linux.deb && dpkg -i vaccel-0.5.0-Linux.deb

# Install Jetson vaccel plugin
RUN wget -q https://s3.nbfc.io/nbfc-assets/github/jetson-plugin/dc6c14f32d96863292e659b1338a7244d15b5504/x86_64/Release/libvaccel-jetson.so -O /usr/local/lib/libvaccel-jetson.so

RUN mkdir -p /usr/local/share/imagenet-models/ && cd /usr/local/share/imagenet-models/ && \
	wget https://s3.nbfc.io/nbfc-assets/github/vaccelrt/plugins/jetson_inference/networks.tar.gz -q -O - | \
	tar -zxvf - -C /usr/local/share/imagenet-models --strip-components=3

ENV VACCEL_IMAGENET_NETWORKS=/usr/local/share/imagenet-models/networks

# Build & install QEMU w/ vAccel backend
RUN git clone https://github.com/cloudkernels/qemu-vaccel.git \
	-b unikraft_vaccelrt && cd qemu-vaccel && \
	git submodule update --init && \
	./configure --extra-cflags="-I /.local/include -Wno-strict-prototypes" --extra-ldflags="-L/.local/lib" --target-list=x86_64-softmmu --enable-virtfs && \
	make -j$(nproc) && make install && \
	cd .. && rm -rf qemu-vaccel
