FROM nubificus/jetson-inference

# Install common build utilities
RUN mkdir /guest && apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get install -yy eatmydata && \
	DEBIAN_FRONTEND=noninteractive eatmydata \
	apt-get install -y --no-install-recommends \
		bison \
		flex \
		build-essential \
		libglib2.0-dev \
		libfdt-dev \
		libpixman-1-dev \
		zlib1g-dev \
		pkg-config \
		iproute2 \
		libcap-ng-dev \
		libattr1-dev \
		genisoimage \
		vim \
		$(apt-get -s build-dep qemu | egrep ^Inst | fgrep '[all]' | cut -d\  -f2) \
	&& rm -rf /var/lib/apt/lists/*

COPY accel.h /usr/include

ARG TOKEN
# Build & install vaccelrti
RUN git clone https://${TOKEN}:x-oauth-basic@github.com/cloudkernels/vaccelrt && \
	cd vaccelrt && git submodule update --init && mkdir build && cd build && \
	cmake -DCMAKE_INSTALL_PREFIX=/.local -DBUILD_PLUGIN_JETSON=ON .. && \
	make && make install && \
	cd ../..
	
# Build & install QEMU w/ vAccel backend
RUN git clone https://${TOKEN}:x-oauth-basic@github.com/cloudkernels/qemu-vaccel.git \
	-b vaccelrt_legacy_virtio && cd qemu-vaccel && \
	git submodule update --init && \
	./configure --extra-cflags="-I /.local/include" --extra-ldflags="-L/.local/lib" --target-list=x86_64-softmmu --enable-virtfs && \
	make -j$(nproc) && make install && \
	cd .. && rm -rf qemu-vaccel

COPY qemu-ifup /etc/qemu-ifup
COPY guest/qemu-guest-x86_64 /data/
